[tools]
cmake = "latest"
python = "3.14"

[env]
_.python.venv = { path = "venv", create = true }


[tasks.requirements]
run = "pip install -r requirements.txt"

[tasks.build_cpp]
run = "cmake -S . -B build && cmake --build build && ./build/pos_cpp"

[tasks.build_python]
run = "cmake -S . -B build && cmake --build build && python src/python/main.py"
# , env = { PYTHONPATH = "{{config_root}}/build" } }
