[tools]
cmake = "latest"
python = "3.14"

[env]
_.python.venv = { path = "venv", create = true }

[tasks]
requirements = "pip install -r requirements.txt"
build = { run = "cmake -S . -B build && cmake --build build && python src/python/main.py", env = { PYTHONPATH = "{{config_root}}/build" } }
